resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:0694b835c5cbffae8bdf61a2a1c72ee2f6632f3f51391eab0e2d2ede9ac4b5bb
  name: controller
  newName: quay.io/goern/r-gespraech-controller
