---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-erinnerung-thoth-station-ninja-v1alpha1-callback
    failurePolicy: Fail
    name: mcallback.kb.io
    rules:
      - apiGroups:
          - erinnerung.thoth-station.ninja
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - callbacks
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-erinnerung-thoth-station-ninja-v1alpha1-callback
    failurePolicy: Fail
    name: vcallback.kb.io
    rules:
      - apiGroups:
          - erinnerung.thoth-station.ninja
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - callbacks
    sideEffects: None
