---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-erinnerung-thoth-station-ninja-v1alpha1-callbackurl
  failurePolicy: Fail
  name: vcallbackurl.kb.io
  rules:
  - apiGroups:
    - erinnerung.thoth-station.ninja
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - callbackurls
  sideEffects: None
