# permissions for end users to edit callbackpayloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: callbackpayload-editor-role
rules:
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbackpayloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbackpayloads/status
  verbs:
  - get
