# permissions for end users to view callbackpayloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: callbackpayload-viewer-role
rules:
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbackpayloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbackpayloads/status
  verbs:
  - get
