---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbackpayloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbackpayloads/finalizers
  verbs:
  - update
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbackpayloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbacks/finalizers
  verbs:
  - update
- apiGroups:
  - erinnerung.thoth-station.ninja
  resources:
  - callbacks/status
  verbs:
  - get
  - patch
  - update
