apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: r-gespraech.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CallbackPayload is storing the actual Payload Data we want to send
        back to any Callback URL. The web services receiving the Payload are determined
        via metav1.LabelSelector `selector`.
      displayName: Callback Payload
      kind: CallbackPayload
      name: callbackpayloads.erinnerung.thoth-station.ninja
      version: v1alpha1
    - description: Callback is the Schema for the callbacks API
      displayName: Callback
      kind: Callback
      name: callbacks.erinnerung.thoth-station.ninja
      statusDescriptors:
      - description: Conditions is the list of error conditions for this resource
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1alpha1
    - description: CallbackUrl is a web service's URL to receive a Callback. The Callback
        Payload to be send to the web service is determined via the metav1.LabelSelector
        `selector`.
      displayName: Callback Url
      kind: CallbackUrl
      name: callbackurls.erinnerung.thoth-station.ninja
      version: v1alpha1
  description: This is a Kubernetes thingy to manage Erinnerungen.
  displayName: r-gespraech
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - erinnerung
  - callback
  links:
  - name: R Gespraech
    url: https://r-gespraech.domain
  maintainers:
  - email: goern@b4mad.net
    name: Christoph Görn
  maturity: alpha
  provider:
    name: goern
  version: 0.0.0
